=== Description des interfaces (PAN1 / PAN2)

// Pour le PAN1, il faut identifier et décrire sommairement toutes les
// interfaces entre modules.

// Pour le PAN2, il faut une description complète des interfaces.

// Il faut ici une description textuelle de chaque interface, c'est-à-dire chaque échange entre deux blocs.
// Si c’est une interface entre deux blocs informatiques, c’est une interface Java.
// S’il y a des échanges de données complexes, il faut en décrire le format avec précision.
// Si c’est une interface entre deux blocs électroniques, c’est une description
// des signaux électroniques ou protocoles utilisés.


==== InterfaceBloc Utilisateur <-> Support <-> Jeu
Le joueur interagit avec différents supports (ordinateur, tablette, smartphone) afin de jouer au jeu par l’intermédiaire d’un navigateur qui reçoit la page web et exécute le jeu.

==== InterfaceBloc Blocs BDD <-> Serveur
Le serveur effectuera des requêtes vers la base de données pour récupérer les ressources pédagogiques et les données utilisateurs.

==== InterfaceBloc Blocs Jeu <-> Serveur
Le jeu sera hébergé sur le serveur conçu en nodejs. Le serveur en nodejs répondra aux requêtes http pour fournir le jeu (page html et scripts javascript) à l’utilisateur, puis pour fournir les media et enregistrer les données utilisateurs.

==== InterfaceBloc Bloc Professionel <-> Jeu <-> BDD : 
Le professionnel nous fournira les informations pour construire le jeu et remplir la base de données de ressources utiles pour informer le joueur.
